### PR TITLE
python 2.7 fixes for numpy 1.15

### PR DESCRIPTION
**Pull request by hmaarrfk**
Fixes the two main warnings.

Also combines https://github.com/scikit-image/scikit-image/pull/3205

## Checklist
[It's fine to submit PRs which are a work in progress! But before they are merged, all PRs should provide:]
- [ ] Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- [ ] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Gallery example in `./doc/examples` (new features only)
- [ ] Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- [ ] Unit tests

[For detailed information on these and other aspects see [scikit-image contribution guidelines](http://scikit-image.org/docs/dev/contribute.html)]

## References
[If this is a bug-fix or enhancement, it closes issue # ]
[If this is a new feature, it implements the following paper: ]

## For reviewers

(Don't remove the checklist below.)

- [ ] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [ ] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.
- [ ] Consider backporting the PR with `@meeseeksdev backport to v0.14.x`

### CODE REVIEW

**Comment by jni** [comment]
Woot, LGTM, let me know if you are ready for me to merge!

**Comment by hmaarrfk** [comment]
yeah it is done.

**Comment by hmaarrfk** [comment]
wait wait

**Comment by hmaarrfk** [comment]
novice backport first. Can you BDFL that. otherwise we will wait for ever for travis.

**Comment by hmaarrfk** [comment]
https://github.com/scikit-image/scikit-image/pull/3320#issuecomment-410532976

**Comment by jni** [comment]
Why don't you roll it into this one?

**Comment by hmaarrfk** [comment]
jinx

**Pull request merged**
